src/templates/block.pug, src/templates/home.pug, src/templates/mixins/index.pug, src/templates/mixins/sciNotation.pug, src/templates/status.pug, src/util/templateFunctions.js
Adding a Scientific Notation function and mixin for use in the pug templates
=> Scientific notation

package-lock.json, package.json, src/public/css/footer.css, src/templates/includes/footer.pug, src/util/templateFunctions.js
=> Add Version and Source at the bottom of the page. 

package-lock.json, src/public/css/footer.css, src/public/css/variables.css, src/templates/includes/footer.pug
updated the mobile footer to have a column layout between the columns for a better UI/UX experience for the user. This will prevent an experience where links are tough to click the correct one when viewing on a mobile device.
=> Mobile footer

src/handlers/block.js, src/templates/block.pug
Fixes #60 - this time with verified commits :)
=> Fix block tx pagination

src/handlers/names.js
Fixes https://github.com/HandshakeAlliance/HNScan/issues/27
=> Fix name pagination and 404 error

src/public/css/navbar.css, src/public/js/index.js, src/templates/includes/navbar.pug
This PR is for issue https://github.com/HandshakeAlliance/HNScan/issues/65. This adds a basic form and should be able to read the basic enter on iphone now (needs verification- I have Android). 
This also adds a hidden button on top of the existing <i> tag to represent the submit button (Bulma doesn't place nicely when it comes to making an <i> a submit button)
=> swapping out catchenter for a submit function

src/public/css/home.css, src/public/misc/robots.txt, src/public/misc/sitemap.xml, src/templates/home.pug, src/templates/includes/meta.pug, src/templates/layouts/layout.pug
- robots.txt
- basic sitemap.xml (500 page max hit)
- It might be worthwhile to pay for a tool to map our _entire_ site... we obviously have more than 500 pages since there's a near infinite number of names/blocks/txs we can hit.
- Open Graph setup (for some social media stuff)
- Added `en` lang tag
- (Hopefully) fixed horizontal scroll issue on homepage
- Added canonical url
=> Shane seo optimization part 1

src/templates/includes/footer.pug, src/templates/includes/meta.pug, src/templates/includes/navbar.pug, src/templates/layouts/layout.pug, src/templates/peers.pug
I was originally going to make a loading optimization PR, but was getting mixed messages from different SEO loading sites on if the TTFB was bad or not. So here are a few more minor updates to hopefully make a few SEO site checkers a little more happy.
This will be my last SEO PR for awhile on HNScan.
=> Shane seo optimization p3 minor standard tweaks

package-lock.json, src/public/css/footer.css, src/public/css/navbar.css, src/public/css/theme-variables.css, src/public/js/index.js, src/templates/includes/footer.pug, src/templates/includes/navbar.pug, src/templates/includes/theme.pug, src/templates/layouts/layout.pug
This stores a checked=true for dark theme and checked=false for light theme and adjusts the slider accordingly [UX Improvement]. Also included in this PR is a fix to the navbar which kept hiding items that wouldn't be visible but you could still click them.
=> responsive theme toggle button in the footer. 

src/handlers/search.js, src/public/css/main.css, src/public/css/navbar.css, src/public/css/search.css, src/public/js/index.js, src/routes.js, src/server.js, src/templates/includes/navbar.pug, src/templates/search.pug
Search revamp, moves us to a search page that can show multiple results, as well as when a result is not found. 
Fixes: #13, #66, #67, #80
=> search: complete revamp

src/public/css/footer.css
=> adding nowrap (footer links shouldnt be wrapping anyway)

src/handlers/search.js, src/public/css/base.css, src/public/css/footer.css, src/public/css/navbar.css, src/templates/includes/navbar.pug, src/templates/name.pug, src/templates/search.pug
Knocking out multiple issues, as well as some minor ui tweaks. All listed below:
- Search tx not working https://github.com/HandshakeAlliance/HNScan/issues/100
- Padding above navbar-items https://github.com/HandshakeAlliance/HNScan/issues/113
- Both mobile and desktop navbar versions impacted
- Empty state for Name History (Simply removing the table header + adding a message when there is no history)
- Changing hover color to theme variable 'link hover' for footer links https://github.com/HandshakeAlliance/HNScan/issues/84
=> Empty states and ui fixes

README.md
This commit adds some clarification about local development and how to use yarn/npm link to rapidly iterate on the backend for new features.
=> readme: update development section

src/components/TransactionList/index.js, src/components/TransactionList/util.js, src/components/shared/PutsList.js, src/containers/TransactionList.js, src/screens/Address.js, src/screens/Block.js, src/screens/Transaction.js, src/util/util.js
This also improves some of the relative imports by switching to absolute imports now allowed by the jsconfig file. 
Will finalize those in the next PR.
=> transactionlist: move to containers

src/App.js, src/components/layout/Footer.js, src/components/layout/Navigation.js
Removes the about page entirely (ignore the branch name :) ) 
Fixes: #52
=> about: remove about page -> redundant to readme

src/components/shared/PutsList.js
Depends on: https://github.com/HandshakeAlliance/hnscan-backend/pull/6
Fixes: #115
=> transactionlist: if input has airdrop flagged, we show a custom input

src/containers/NodeMap.js
=> PeersMap: making the map interactive with amcharts zoom control buttons

.github/workflows/deploy.yml, package.json, public/CNAME
=> wip: Deploy workflow

package.json, yarn.lock
Runs prettier automatically on staged files to ensure that they are formatted correctly before committing.
=> dev: add lint-staged hook 

src/components/address/AddressSummary.js
=> address: flip balance and received

README.md
=> readme: bump development title size

src/components/layout/Footer.js
=> footer: replace div.field with sc that has same margin.

.env.production, .github/workflows/deploy.yml, yarn.lock
=> deploy: test using github pages deploy and removing env.production

package.json, src/screens/Settings.js, yarn.lock
* trying to get the lng switcher fnc to work
* adding 'false' to useLocalStorage
* ucl: bumping ucl
* i18n: removing console log and comment
=> chore: sync master

package.json, src/components/App.js, src/components/layout/Footer.js, src/components/layout/Navigation.js, src/containers/charts/DailyDifficulty.js, src/i18n/en/en.json, src/screens/tools/Charts.js, yarn.lock
=> feature: add initial commit for difficulty chart

src/components/App.js, src/screens/errors/NetworkBoundary.js
This allows users to change their network config if hnscan can't find a valid node connection.
=> errors: add a network boundary
